# Change these first
owner: DigitalVoiceNZ # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: DVNZ
    url: https://dvnz.nz
  - name: XLX299
    url: https://xlx299.nz
  - name: M17-NZD
    url: https://m17-nzd.dvnz.nz
  - name: XLX530
    url: http://zldigitalreflectors.hopto.org:84/
  - name: XLX327
    url: http://xlx327.from-ak.com
  - name: HBlink
    url: https://hblink.dvnz.nz
  - name: Allmon
    url: https://allstarnz.dvnz.nz
  - name: IPSC2-ZL
    url: http://dmrplus.arec.info/ipsc 
  - name: ZL1OTD Repeater
    url: https://zl1otd.dvnz.nz
  - name: ZL1AMK Repeater
    url: http://zl1amk.ddns.net:82
  - name: ZL2ROR Repeater
    url: https://zl2ror.dvnz.nz  
  - name: FreeDMR-NZ
    url: https://freedmr.dvnz.nz
  - name: ZL4GQ Repeater
    url: zl4gq.dvnz.nz



status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dvnz.nz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/digitalvoicenz/upptime/master/static/img/dvnz-48.png
  name: DVNZ Status
  introTitle: "Digital Voice NZ Reflectors and Repeaters"
  introMessage: Server status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
