# Change these first
owner: DigitalVoiceNZ # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: DVNZ
    url: https://dvnz.nz
  - name: XLX299
    url: https://xlx299.nz
  - name: XLX936
    url: https://xlx.dvnz.nz
  - name: XLX626
    url: https://xlx626.onjapan.net
  - name: HBlink
    url: http://hblink.dvnz.nz
  - name: M17-299
    url: https://m17.dvnz.nz
  - name: ZL1HXD Repeater 
    url: http://www.zl1hxd.duckdns.org:82/
  - name: ZL1OTD Repeater
    url: https://zl1otd.dvnz.nz/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dvnz.nz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/digitalvoicenz/upptime/master/static/img/dvnz-48.png
  name: DVNZ Status
  introTitle: "Digital Voice NZ Reflectors and Repeaters"
  introMessage: Server status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
